#version 430 core

layout (local_size_x = 1, local_size_y = 1) in;

layout (rg32f, binding=0) uniform image2D data;

uniform vec4 a = vec4(1);
uniform vec4 b = vec4(0);

void main(void){
	int i = int(gl_GlobalInvocationID.x);
	int j = int(gl_GlobalInvocationID.y);

	vec4 color = a;
	if(((i/8)%2 == 0) && ((j/8)%2 == 0) || ((i/8)%2 != 0) && ((j/8)%2 != 0)){
		color = b;
	}
	imageStore(data, ivec2(gl_GlobalInvocationID.xy), color);
}